age=input('what is your age? ')
age=int(age)
birthyear=(2018-age)
deathyear=(birthyear+79)
print(deathyear)
print('-'*80)
print('Morbid Predictions Program:')
print('Description: This program asks you for your current age and tells you the year that you will die (on average).')
print()
age= input('What is your age today? ')
age= int(age)
print('...thinking...')
print('...thinking...')
print('...thinking...')
print('You will die in the year...')
birthyear= 2018 - age
birthyear= int(birthyear)
answer= birthyear + 79
answer= int(answer)
print(answer)
print('-'*80)
